services:
  ia_docker:
    hostname:         ia_docker.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_docker:latest
    restart:          no
    logging:
      driver:         syslog   
