services:
  ia_docker:
    hostname:         ia_docker.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_docker:latest
        -           ia_docker:latest
        - innovanon/ia_docker
        -           ia_docker
    image:            innovanon/ia_docker
    restart:          no
    logging:
      driver:         syslog   
